#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
dry_run=false
no_start=false
for argument in "$@"; do
  case "$argument" in
    --dry-run) dry_run=true ;;
    --no-start) no_start=true ;;
    -h|--help)
      echo "Usage: sudo ./scripts/install.sh [--dry-run] [--no-start]"
      exit 0
      ;;
    *) echo "Unknown option: $argument" >&2; exit 2 ;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run this installer with sudo." >&2
  exit 1
fi

env_file=/etc/chatinabox/chatinabox.env
if [[ -f "$env_file" ]]; then
  env_owner="$(stat -c '%u' "$env_file")"
  env_mode="$(stat -c '%a' "$env_file")"
  if [[ "$env_owner" != 0 || ( "$env_mode" != 600 && "$env_mode" != 640 ) ]]; then
    echo "Refusing to load unsafe existing environment: $env_file" >&2
    echo "Expected root ownership and mode 600 or 640." >&2
    exit 1
  fi
  set -a
  # This file is generated by Chatinabox as simple KEY=value entries.
  source "$env_file"
  set +a
fi

printf '\n› Checking the host\n'

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    return 1
  fi
}

need node
need npm
need tmux
need codex
need systemctl

node_major="$(node -p 'Number(process.versions.node.split(".")[0])')"
if (( node_major < 22 )); then
  echo "Node.js 22 or newer is required; found $(node --version)." >&2
  exit 1
fi

codex_help="$(codex --help 2>&1)"
for required_flag in \
  --dangerously-bypass-approvals-and-sandbox \
  --dangerously-bypass-hook-trust
do
  if [[ "$codex_help" != *"$required_flag"* ]]; then
    echo "This Codex CLI does not support $required_flag." >&2
    echo "Update Codex, then retry." >&2
    exit 1
  fi
done
if ! codex login status >/dev/null 2>&1; then
  echo "Codex is not logged in for root, which owns Chatinabox sessions." >&2
  echo "Run sudo codex login, then retry." >&2
  exit 1
fi

convert_path="${CHATINABOX_CONVERT_PATH:-}"
if [[ -z "$convert_path" ]] && command -v convert >/dev/null 2>&1; then
  convert_path="$(command -v convert)"
fi

chrome_path="${CHATINABOX_CHROME_PATH:-}"
if [[ -z "$chrome_path" ]]; then
  for candidate in \
    /usr/bin/google-chrome \
    /opt/google/chrome/chrome \
    /usr/bin/chromium \
    /usr/bin/chromium-browser
  do
    if [[ -x "$candidate" ]]; then chrome_path="$candidate"; break; fi
  done
fi
if [[ -z "$chrome_path" || ! -x "$chrome_path" ]]; then
  chrome_path=""
fi
if [[ -z "$convert_path" || ! -x "$convert_path" || -z "$chrome_path" ]]; then
  echo "Note: /screen needs both ImageMagick and Chrome/Chromium."
  echo "Chat, sessions, setup, and deployment do not depend on it."
fi

scribe_api_key="${ELEVENLABS_API_KEY:-}"
scribe_language="${CHATINABOX_SCRIBE_LANGUAGE:-eng}"
scribe_keyterms="${CHATINABOX_SCRIBE_KEYTERMS:-}"

printf '\n› Building and testing Chatinabox\n'
(
  cd "$repo_dir"
  npm ci
  npm run verify
)

if $dry_run; then
  echo
  echo "Dry run passed. No system files or services were changed."
  exit 0
fi

printf '\n› Installing the release\n'

bot_token="${CHATINABOX_TG_BOT_TOKEN:-${TG_BOT_TOKEN:-}}"
owner_ids="${CHATINABOX_TG_USER_ID:-${TG_ALLOWED_USER_IDS:-}}"
if [[ -z "$bot_token" ]]; then
  read -r -s -p "Telegram bot token from @BotFather: " bot_token
  echo
fi
if [[ -z "$owner_ids" ]]; then
  read -r -p "Your numeric Telegram user ID: " owner_ids
fi
if [[ ! "$bot_token" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]]; then
  echo "The Telegram bot token does not look valid." >&2
  exit 1
fi
if [[ ! "$owner_ids" =~ ^[1-9][0-9]*(,[1-9][0-9]*)*$ ]]; then
  echo "Use one numeric Telegram ID, or a comma-separated list." >&2
  exit 1
fi

if ! getent group chatinabox >/dev/null; then
  groupadd --system chatinabox
fi
if ! id chatinabox >/dev/null 2>&1; then
  useradd --system --gid chatinabox --home-dir /var/lib/chatinabox \
    --shell /usr/sbin/nologin chatinabox
fi

install -d -m 0755 /opt/chatinabox/releases
install -d -o chatinabox -g chatinabox -m 0700 /var/lib/chatinabox
install -d -o root -g root -m 0700 /var/lib/chatinabox-bridge
install -d -o root -g chatinabox -m 0770 /run/chatinabox
install -d -m 0755 /etc/chatinabox

release_id="$(date -u +%Y%m%dT%H%M%S%NZ)-$(git -C "$repo_dir" rev-parse --short HEAD 2>/dev/null || echo local)"
release_dir="/opt/chatinabox/releases/$release_id"
install -d -m 0755 "$release_dir"
cp -a "$repo_dir/dist" "$repo_dir/bin" "$repo_dir/ops" \
  "$repo_dir/package.json" "$repo_dir/package-lock.json" "$release_dir/"
chmod +x "$release_dir/bin/chatinabox" "$release_dir/ops/chatinabox-command"
(
  cd "$release_dir"
  npm ci --omit=dev
)
# The installer may inherit a restrictive operator umask. Release code contains
# no secrets and must remain readable/traversable by the unprivileged service.
chmod -R a+rX "$release_dir"

node_path="$(command -v node)"
codex_path="$(command -v codex)"
tmux_path="$(command -v tmux)"
profile_path=/etc/chatinabox/profile.json
if [[ ! -e "$profile_path" ]]; then
  install -o root -g root -m 0644 \
    "$repo_dir/ops/chatinabox-profile.json" "$profile_path"
fi
install -o root -g chatinabox -m 0640 /dev/null "$env_file"
{
  printf 'TG_BOT_TOKEN=%s\n' "$bot_token"
  printf 'TG_ALLOWED_USER_IDS=%s\n' "$owner_ids"
  printf 'CHATINABOX_DATA_DIR=%s\n' "${CHATINABOX_DATA_DIR:-/var/lib/chatinabox}"
  printf 'CHATINABOX_BRIDGE_SOCKET=%s\n' "${CHATINABOX_BRIDGE_SOCKET:-/run/chatinabox/bridge.sock}"
  printf 'CHATINABOX_BRIDGE_DB=%s\n' "${CHATINABOX_BRIDGE_DB:-/var/lib/chatinabox-bridge/bridge.sqlite}"
  printf 'CHATINABOX_DEFAULT_CWD=%s\n' "${CHATINABOX_DEFAULT_CWD:-/root}"
  printf 'CHATINABOX_WORKSPACE_ROOTS=%s\n' "${CHATINABOX_WORKSPACE_ROOTS:-/root}"
  printf 'CHATINABOX_LOBBY_CWD=%s\n' "${CHATINABOX_LOBBY_CWD:-/var/lib/chatinabox-bridge/lobby}"
  printf 'CHATINABOX_PROFILE_PATH=%s\n' "$profile_path"
  printf 'CHATINABOX_CODEX_PATH=%s\n' "$codex_path"
  printf 'CHATINABOX_TMUX_PATH=%s\n' "$tmux_path"
  printf 'CHATINABOX_CONVERT_PATH=%s\n' "$convert_path"
  printf 'CHATINABOX_CHROME_PATH=%s\n' "$chrome_path"
  if [[ -n "$scribe_api_key" ]]; then
    printf 'ELEVENLABS_API_KEY=%s\n' "$scribe_api_key"
    printf 'CHATINABOX_SCRIBE_LANGUAGE=%s\n' "$scribe_language"
    if [[ -n "$scribe_keyterms" ]]; then
      printf 'CHATINABOX_SCRIBE_KEYTERMS=%s\n' "$scribe_keyterms"
    fi
  fi
} > "$env_file"
chown root:chatinabox "$env_file"
chmod 0640 "$env_file"

install -m 0644 "$repo_dir/ops/systemd/chatinabox-bridge.service" \
  /etc/systemd/system/chatinabox-bridge.service
install -m 0644 "$repo_dir/ops/systemd/chatinabox.service" \
  /etc/systemd/system/chatinabox.service
if [[ "$node_path" != /usr/bin/node ]]; then
  sed -i "s|/usr/bin/node|$node_path|g" \
    /etc/systemd/system/chatinabox-bridge.service \
    /etc/systemd/system/chatinabox.service \
    "$release_dir/ops/codex-hooks.json"
fi
install -m 0755 "$repo_dir/ops/chatinabox-command" /usr/local/bin/chatinabox

install -d -m 0700 /root/.codex
node "$repo_dir/ops/install-codex-hooks.mjs" \
  "$release_dir/ops/codex-hooks.json" /root/.codex/hooks.json
node "$repo_dir/ops/install-chatinabox-instructions.mjs" \
  "$repo_dir/ops/chatinabox-global-AGENTS-block.md" \
  /root/.codex/AGENTS.md /root/AGENTS.md
install -d -o root -g root -m 0700 /var/lib/chatinabox-bridge/lobby
manager_cwd="$(
  CHATINABOX_PROFILE_FILE="$profile_path" \
    CHATINABOX_RELEASE_PROFILE_MODULE="$release_dir/dist/vps/experience-profile.js" \
    node -e \
    'const p=require(process.env.CHATINABOX_RELEASE_PROFILE_MODULE); process.stdout.write(p.readExperienceProfile(process.env.CHATINABOX_PROFILE_FILE).manager.cwd)'
)"
install -d -o root -g root -m 0700 "$manager_cwd"
install -o root -g root -m 0600 \
  "$repo_dir/ops/chatinabox-lobby-AGENTS.md" \
  /var/lib/chatinabox-bridge/lobby/AGENTS.md
install -o root -g root -m 0600 \
  "$repo_dir/ops/chatinabox-manager-AGENTS.md" \
  "$manager_cwd/AGENTS.md"

printf '\n› Configuring Telegram\n'

# Polling and webhooks are mutually exclusive. The bot also owns its concise
# command menu and public description.
TG_BOT_TOKEN="$bot_token" node "$repo_dir/scripts/configure-telegram.mjs"

previous_release="$(readlink -f /opt/chatinabox/current 2>/dev/null || true)"
release_switched=false
install_complete=false
rollback_release() {
  if $release_switched && ! $install_complete; then
    echo "Install failed after activation; restoring the previous release." >&2
    if [[ -n "$previous_release" && -d "$previous_release" ]]; then
      ln -sfn "$previous_release" /opt/chatinabox/current
      systemctl daemon-reload || true
      systemctl restart chatinabox-bridge.service chatinabox.service || true
    else
      unlink /opt/chatinabox/current 2>/dev/null || true
    fi
  fi
}
trap rollback_release ERR
ln -sfn "$release_dir" /opt/chatinabox/current
release_switched=true

systemctl daemon-reload
systemctl enable chatinabox-bridge.service chatinabox.service >/dev/null
if ! $no_start; then
  printf '\n› Starting Chatinabox\n'
  systemctl restart chatinabox-bridge.service
  systemctl restart chatinabox.service
  sleep 2
  /usr/local/bin/chatinabox doctor
fi
install_complete=true
trap - ERR

echo
echo "Chatinabox installed. Open your bot in Telegram and send /start."
if $no_start; then
  echo "Services were installed but not started; run: systemctl start chatinabox-bridge chatinabox"
fi
